### PR TITLE
Use new redis-sharelatex instead of RedisBackend for cluster abstraction

### PR DESCRIPTION
**Pull request by jpallen**

### CODE REVIEW

**Comment by briangough** [comment]
Looks good, consider merging in bg-redis-cluster-refactor to update the name of the redis client in the acceptance tests for consistency.

**Comment by jpallen** [comment]
Hmm, good catch. Not intentional, my mental model is all wrong :( Lock doesn't map nicely to 'realtime', 'documentupdater' or 'history'. Might create a new 'lock' category, but it's all getting a bit messy. Thoughts?

**Comment by jpallen** [comment]
Updated now, and run all acceptance tests against cluster config as well as defaults (cluster is left commented out in setings)

**Comment by briangough** [comment]
:+1:

**Pull request merged**
